In [39]:
import torch
from torch import nn
import torch.nn.functional as f
from torch.optim import Adam
torch.__version__

'2.7.0'

In [40]:
from torch.utils.data import DataLoader, TensorDataset
import lightning as L

In [41]:
token_to_id = {"what" : 0, "is": 1, "statquest": 2, "awesome": 3, "<EOS>": 4}

token_to_id

{'what': 0, 'is': 1, 'statquest': 2, 'awesome': 3, '<EOS>': 4}

In [42]:
id_to_token = dict(map(reversed, token_to_id.items()))
id_to_token

{0: 'what', 1: 'is', 2: 'statquest', 3: 'awesome', 4: '<EOS>'}

In [43]:
inputs = torch.tensor([[token_to_id["what"],
           token_to_id["is"],
           token_to_id["statquest"],
           token_to_id["<EOS>"],
           token_to_id["awesome"]],
          
          [token_to_id["statquest"],
           token_to_id["is"],
           token_to_id["what"],
           token_to_id["<EOS>"],
           token_to_id["awesome"]]
          ])

inputs




tensor([[0, 1, 2, 4, 3],
        [2, 1, 0, 4, 3]])

In [44]:
labels = torch.tensor([[
           token_to_id["is"],
           token_to_id["statquest"],
           token_to_id["<EOS>"],
           token_to_id["awesome"],
           token_to_id["<EOS>"]],
          
          [
           token_to_id["is"],
           token_to_id["what"],
           token_to_id["<EOS>"],
           token_to_id["awesome"],
           token_to_id["<EOS>"]]
          ])


In [45]:
inputs , labels

(tensor([[0, 1, 2, 4, 3],
         [2, 1, 0, 4, 3]]),
 tensor([[1, 2, 4, 3, 4],
         [1, 0, 4, 3, 4]]))

In [46]:
dataset = TensorDataset(inputs, labels)
dataset

In [47]:
dataloader = DataLoader(dataset)

In [48]:
next(iter(dataloader))

[tensor([[0, 1, 2, 4, 3]]), tensor([[1, 2, 4, 3, 4]])]

In [56]:
pe = torch.zeros(6,4)

In [55]:
torch.arange(0, 6).float().unsqueeze(1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])

In [57]:
pe

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
pe[:, 0::2]

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])