In [1]:
import torch

In [8]:
text = open("shakes.txt", "r")

In [9]:
text = text.read()

In [12]:
print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [13]:
len(text)

1115394

In [18]:
chars = sorted(list(set(text)))

vocab_size = len(chars)
vocab_size

65

In [19]:
stoi = {val: i for i, val in enumerate(chars)}
stoi

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [20]:
itos = dict(map(reversed, stoi.items()))

itos

{0: '\n',
 1: ' ',
 2: '!',
 3: '$',
 4: '&',
 5: "'",
 6: ',',
 7: '-',
 8: '.',
 9: '3',
 10: ':',
 11: ';',
 12: '?',
 13: 'A',
 14: 'B',
 15: 'C',
 16: 'D',
 17: 'E',
 18: 'F',
 19: 'G',
 20: 'H',
 21: 'I',
 22: 'J',
 23: 'K',
 24: 'L',
 25: 'M',
 26: 'N',
 27: 'O',
 28: 'P',
 29: 'Q',
 30: 'R',
 31: 'S',
 32: 'T',
 33: 'U',
 34: 'V',
 35: 'W',
 36: 'X',
 37: 'Y',
 38: 'Z',
 39: 'a',
 40: 'b',
 41: 'c',
 42: 'd',
 43: 'e',
 44: 'f',
 45: 'g',
 46: 'h',
 47: 'i',
 48: 'j',
 49: 'k',
 50: 'l',
 51: 'm',
 52: 'n',
 53: 'o',
 54: 'p',
 55: 'q',
 56: 'r',
 57: 's',
 58: 't',
 59: 'u',
 60: 'v',
 61: 'w',
 62: 'x',
 63: 'y',
 64: 'z'}

In [23]:
encode = lambda x : [stoi[i] for i in x]
decode = lambda x : "".join([itos[i] for i in x])

decode(encode("hello"))

'hello'

In [33]:
# Now we have the tokenizer, encode all the text

data = torch.tensor(encode(text))
print(data[:500])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

In [29]:
data.shape, data.dtype

(torch.Size([1115394]), torch.int64)

In [36]:
#since we dont have test dataset
n = int(0.9*len(text))
n

train_data = data[:n]
val_data =  data[n:]

In [37]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [39]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

x, y

(tensor([18, 47, 56, 57, 58,  1, 15, 47]),
 tensor([47, 56, 57, 58,  1, 15, 47, 58]))

In [41]:
for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print(f"The contxt is : {context} and target is : {target}")

The contxt is : tensor([18]) and target is : 47
The contxt is : tensor([18, 47]) and target is : 56
The contxt is : tensor([18, 47, 56]) and target is : 57
The contxt is : tensor([18, 47, 56, 57]) and target is : 58
The contxt is : tensor([18, 47, 56, 57, 58]) and target is : 1
The contxt is : tensor([18, 47, 56, 57, 58,  1]) and target is : 15
The contxt is : tensor([18, 47, 56, 57, 58,  1, 15]) and target is : 47
The contxt is : tensor([18, 47, 56, 57, 58,  1, 15, 47]) and target is : 58


In [42]:
# now lets create batchs
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # [1,2,3,4]
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y
    
    

In [45]:
xb , yb = get_batch("train")

xb.shape

torch.Size([4, 8])

In [68]:
from torch import nn
torch.manual_seed(42)

emmb = nn.Embedding(65,65)

emmb.state_dict()


OrderedDict([('weight',
              tensor([[ 1.9269,  1.4873,  0.9007,  ..., -1.1845,  1.3835,  1.4451],
                      [ 0.8564,  2.2181,  0.5232,  ...,  0.4114,  1.9312,  1.0119],
                      [-1.4364, -1.1299, -0.1360,  ...,  1.7744, -0.9216,  0.9624],
                      ...,
                      [ 0.2824, -0.8111, -1.5486,  ...,  2.6678, -0.1403,  0.9416],
                      [-0.0118, -0.5197,  1.8524,  ...,  0.8935, -1.5114, -0.8515],
                      [ 2.0818,  1.0677, -1.4277,  ..., -1.4058,  0.4083, -1.5780]]))])

In [84]:
sam = torch.rand(4,8,65)

In [93]:
emmb(torch.tensor([[2,3,4]])).shape

torch.Size([1, 3, 65])

In [105]:
weights = torch.tensor([20, 100, 300, 30], dtype=torch.float)
torch.multinomial(weights, 1)

tensor([1])

In [106]:
import torch
from torch import nn
from torch.nn import functional as f 
torch.manual_seed(42)

class BiagramModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
        
    def forward(self, idx, target=None):
        logit = self.token_embedding_table(idx)
        
        if target is None:
            loss =  None
        else:
            B,T,C = logit.shape
            logit = logit.view(B*T, C)
            target = target.view(B*T) 
            loss = f.cross_entropy(logit, target)
        return logit, loss
    def generate(self, idx, max_tokens): 
        for _ in range(max_tokens):
            logits, _ = self(idx)
            logits = logits[:,-1,:]
            probs = f.softmax(logits,1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx,idx_next), 1)
        
        return idx
    

In [109]:
m = BiagramModel(vocab_size=vocab_size)
m(xb,yb)

(tensor([[-0.0161,  0.1193, -0.7611,  ..., -1.1184,  0.2578,  0.5527],
         [-0.1347, -0.3754,  0.2636,  ...,  0.4949, -0.2564,  0.3443],
         [-0.1347, -0.3754,  0.2636,  ...,  0.4949, -0.2564,  0.3443],
         ...,
         [-0.2399,  0.6579,  0.2116,  ..., -0.8621,  0.7030, -0.6684],
         [ 2.1492,  1.4239, -1.8003,  ...,  0.4980,  1.0775, -0.0354],
         [ 1.2218, -0.1315,  0.6742,  ..., -0.9429, -0.2941,  0.3058]],
        grad_fn=<ViewBackward0>),
 tensor(4.4742, grad_fn=<NllLossBackward0>))