In [2]:
import tensorflow as tf

tf.__version__

'2.19.0'

In [6]:
tf.math.add([10,20], [30,50])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([40, 70], dtype=int32)>

In [7]:
tf.math.square(10)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [12]:
tf.math.reduce_sum([1, 2, 3], axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [14]:
tf.math.square(2) + tf.math.square(3)


<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [15]:
x = tf.linalg.matmul([[1]], [[2, 3]])
print(x)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)


In [17]:
tf.constant([[1]]).shape , tf.constant( [[2, 3]]).shape

(TensorShape([1, 1]), TensorShape([1, 2]))

In [18]:
import numpy as np

a = np.array([1,2,3])

a

array([1, 2, 3])

In [20]:
b = tf.multiply(a, 10)
b

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([10, 20, 30])>

In [22]:
np.add(b , 100)

array([110, 120, 130])

In [24]:
x = tf.random.uniform(shape=(2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.01085019, 0.6744412 , 0.62967443],
       [0.25179482, 0.8528135 , 0.8007871 ]], dtype=float32)>

In [35]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [31]:
x.device.endswith("CPU:0")

True

In [34]:
x.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [36]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [39]:
next(iter(ds_tensors))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [41]:
next(iter(ds_file))

<tf.Tensor: shape=(), dtype=string, numpy=b'Line 1'>

In [42]:
print("Tensor Dataset:")
for item in ds_tensors:
    print(item.numpy())

print("\nFile Dataset:")
for line in ds_file:
    print(line.numpy().decode('utf-8'))


Tensor Dataset:
1
2
3
4
5
6

File Dataset:
Line 1
Line 2
Line 3
  


2025-06-04 11:25:57.762781: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
