In [1]:
import torch

torch.__version__

'2.7.0'

In [15]:
f32_tensor = torch.rand(1000)
f32_tensor,  f32_tensor.dtype


(tensor([0.8203, 0.4435, 0.5055, 0.5924, 0.0426, 0.9559, 0.6908, 0.3116, 0.7230,
         0.4969, 0.1197, 0.5499, 0.3050, 0.8783, 0.8994, 0.5293, 0.7909, 0.9391,
         0.0901, 0.9838, 0.3014, 0.3568, 0.5751, 0.5559, 0.0455, 0.0868, 0.3637,
         0.5922, 0.8982, 0.3962, 0.3061, 0.3714, 0.2269, 0.2323, 0.2362, 0.6883,
         0.6902, 0.3222, 0.8458, 0.8176, 0.5548, 0.6868, 0.9114, 0.1159, 0.4751,
         0.2089, 0.5888, 0.8328, 0.8044, 0.1914, 0.9475, 0.3751, 0.2815, 0.5507,
         0.8902, 0.7966, 0.5378, 0.2708, 0.3217, 0.3237, 0.1050, 0.6682, 0.2866,
         0.6284, 0.5913, 0.6075, 0.0453, 0.7306, 0.3362, 0.6744, 0.8700, 0.0677,
         0.2628, 0.2855, 0.7511, 0.2993, 0.3851, 0.8686, 0.7173, 0.7700, 0.4645,
         0.2263, 0.0670, 0.2518, 0.6225, 0.0304, 0.3626, 0.1869, 0.5424, 0.4803,
         0.3571, 0.3117, 0.8723, 0.5594, 0.3218, 0.5823, 0.0824, 0.9371, 0.9613,
         0.2546, 0.6014, 0.2061, 0.3777, 0.7145, 0.9652, 0.7452, 0.6645, 0.9283,
         0.2326, 0.6818, 0.9

In [16]:
torch.dot(f32_tensor,  f32_tensor)

tensor(342.5364)

In [17]:
# Down casting

bf16_tensor = f32_tensor.to(dtype=torch.bfloat16)

bf16_tensor ,  bf16_tensor.dtype

torch.dot(bf16_tensor, bf16_tensor)




tensor(342., dtype=torch.bfloat16)

In [18]:
import tensorflow as tf

f32_tensor = tf.random.uniform(shape=(5,))
f32_tensor

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.9889715 , 0.3431121 , 0.4127611 , 0.02750146, 0.669865  ],
      dtype=float32)>

In [19]:
bf16_tensor = tf.cast(f32_tensor, tf.bfloat16)

bf16_tensor

<tf.Tensor: shape=(5,), dtype=bfloat16, numpy=array([0.988281, 0.34375, 0.412109, 0.0274658, 0.667969], dtype=bfloat16)>

In [24]:
tf.tensordot(bf16_tensor, bf16_tensor, axes=1)

<tf.Tensor: shape=(), dtype=bfloat16, numpy=1.7109375>